### ISSUE TITLE
On ios, it looks not working

### ISSUE THREAD

**Issue by spartaheonil** [sbbullet/videojs-dynamic-watermark#2]
Hello, I have problems when using this, my iphone can't show watermark on full screen. In MacOS and andriod. it works well!

**Comment by sbbullet** [comment]
@spartaheonil , if you are using VHS, you must override the native behavior like this
```js
var player = videojs('playerId', {
  html5: {
    vhs: {
      overrideNative: true
    },
    nativeAudioTracks: false,
    nativeVideoTracks: false
  }
});
```
Read more at : https://github.com/videojs/http-streaming#overridenative

**Comment by spartaheonil** [comment]
yes i did it. but it looks not working.

below is my videojs option.

```html5: {
      vhs: {
        overrideNative: true,
        cacheEncryptionKeys: true,
      },
      nativeAudioTracks: false,
      nativeVideoTracks: false,
    },
```

**Comment by sbbullet** [comment]
It's a platform limitation then.

From the author himself in [this thread](https://github.com/videojs/video.js/issues/6257#issuecomment-539085923)
> Unfortunately, there isn't anything that can be done on iOS beyond disabling the fullscreen button. Chrome on iOS will always use the native player. Safari will use the native player on iPhones but it should take the player fullscreen on iPads with version 12 and newer.

If you badly need this to be implemented, try disabling the full-screen control in the iOS devices and use `fullWindow()` instead for fullscreen like experience as mentioned in the thread I've mentioned above.
