### ISSUE TITLE
Containing Watermark inside the video's width & height

### ISSUE THREAD

**Issue by ShanArosh** [sbbullet/videojs-dynamic-watermark#3]
First of I should say your library and implementation are excellent. Love it !! 
Is there any way to get the original video height and width to prevent the watermark from appearing outside of the video?

[videojs.webm](https://github.com/sbbullet/videojs-dynamic-watermark/assets/96517136/d8bdaf93-895d-48e7-b841-59b029a10f18)

**Comment by ShanArosh** [comment]
Checkout the pull request on https://github.com/sbbullet/videojs-dynamic-watermark/pull/5

**Comment by sbbullet** [comment]
Thanks @ShanArosh for the PR. I'll look into it this weekend we'll merge it ASAP and publish new fixed version.

**Comment by sbbullet** [comment]
Closed #5
